### ISSUE TITLE
HTTP chunks instead of WebSockets

### ISSUE THREAD

**Issue by victorbalan** [coduno/api#71]
We decided to use HTTP chunks instead of WebSockets but I think we have a problem. [This] (https://groups.google.com/forum/#!msg/golang-nuts/nIaN09QmE3k/ohmbp4uhv6QJ) states that we cannot flush our `http.ResponseWriter` and due to that we cannot get the progress in the xhr request from the client. 

I'd suggest sending back the list of tests that are pending in the `POST /results/submission` request. Every `test.Call(...)` will be a separate go routine that will add the results to memcache once they are finished. We can pool every 10 seconds to get the results and the pending tests from there. WDYT?

**Comment by flowlo** [comment]
I will give it a try and make the App Engine implementation a http.Flusher. If that does not work, your proposal is our last resort.

**Comment by flowlo** [comment]
Closing as we're now using a WebSocket proxy and this works reasonably well.
